server:
  port: 9001

spring:
  application:
    name: auth-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
  renewalPercentThreshold: 0.85

jwt:
  secret: giGacHadsecretSSSgulRankNoThisKeyWasTooSmallAndIaArtificiallyLengthenedIt
  expiration: 86400

service:
  user-service:
    get-user: http://user-service/users
    post-user: http://user-service/users
    is-exist: http://user-service/users/is-exist
    is-correct: http://user-service/users/is-correct